// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeR0_n2UiSF-qEw0Wt1EVPQhg73RQr-Cc',
    appId: '1:345403329261:web:47ffaf0649c2c6564a9ae4',
    messagingSenderId: '345403329261',
    projectId: 'fixmasters-17b0f',
    authDomain: 'fixmasters-17b0f.firebaseapp.com',
    storageBucket: 'fixmasters-17b0f.appspot.com',
    measurementId: 'G-H4PHY82XQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmadBWNPfkXmykYx_huDb2U58kLKswGfA',
    appId: '1:345403329261:android:c032e5c9000c682f4a9ae4',
    messagingSenderId: '345403329261',
    projectId: 'fixmasters-17b0f',
    storageBucket: 'fixmasters-17b0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTrjO27elnmgxeoB0u58f2IzZhxg9lk8',
    appId: '1:345403329261:ios:1c2400ea6128241e4a9ae4',
    messagingSenderId: '345403329261',
    projectId: 'fixmasters-17b0f',
    storageBucket: 'fixmasters-17b0f.appspot.com',
    iosBundleId: 'com.naodtadele.fixmastersUserApp',
  );
}
